- name: Create Spark master systemd service file
  template:
    src: spark-master.service.j2
    dest: /etc/systemd/system/spark-master.service

- name: Reload systemd and start Spark master service
  systemd:
    name: spark-master
    daemon_reload: yes
    state: started
    enabled: yes