- name: Create Spark worker systemd service file
  template:
    src: spark-worker.service.j2
    dest: /etc/systemd/system/spark-worker.service

- name: Reload systemd and start Spark worker service
  systemd:
    name: spark-worker
    daemon_reload: yes
    state: started
    enabled: yes